# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sLJmYTz83DbLpBk_Dfi2sNfhAHikdmYA
"""

pip install schedule

!pip install --force-reinstall jsonschema==3.2.0

pip install web3

pip install kafka-python

from web3 import Web3
from web3.middleware import geth_poa_middleware

from kafka import KafkaProducer
import json
#from config.kafka_config import *

producer = KafkaProducer(
 bootstrap_servers="kafka-deqode-0c18.aivencloud.com"+":"+str(21780),
 security_protocol="SSL",
 ssl_cafile="ca.pem",
 ssl_certfile="service.cert",
 ssl_keyfile="service.key",
 value_serializer=lambda v: json.dumps(v).encode('ascii'),
 key_serializer=lambda k: json.dumps(k).encode('ascii')
)

topic_name = 'Address'

def web3Functions(block): 
    #data = []
    web3 = Web3(Web3.WebsocketProvider("wss://mainnet.infura.io/ws/v3/57d8e5ec16764a3e86ce18fc505e640e"))
    web3.middleware_onion.inject(geth_poa_middleware, layer=0) 
    for tx_hash in web3.eth.get_block(block).transactions:
        contractAddress = web3.eth.getTransactionReceipt(tx_hash).contractAddress
        #print(contractAddress)
        if contractAddress != None:
          print(contractAddress, block)
          #data.append((contractAddress, block))
          kafkaData(contractAddress,block)
    del web3
    del block

def kafkaData(contractAddress,block):
  producer.send(
      topic_name,
      #key={"id": count},
      value={"address":contractAddress, "block":block}
  )

web3 = Web3(Web3.WebsocketProvider("wss://mainnet.infura.io/ws/v3/57d8e5ec16764a3e86ce18fc505e640e"))
web3.middleware_onion.inject(geth_poa_middleware, layer=0) 
block= web3.eth.get_block('latest').number + 1
del web3
while block>=0:
    block-=1
    web3Functions(block)

producer.send(
 topic_name,
 key={"id":1},
 value={"name":"Francesco", "pizza":"Margherita"}
)

#producer.flush()

producer.send(
 topic_name,
 key={"id":2},
 value={"name":"👩 Adele", "pizza":"Hawaii 🍕+🍍+🥓"}
)

producer.send(
 topic_name,
 key={"id":3},
 value={"name":"👦 Mark", "pizza":"Choccolate 🍕+🍫"}
)

producer.flush()

topic_name,
 key={"id":4},
 value={"name":"👨 Dan", "pizza":"Fries 🍕+🍟"}
)
producer.flush()